### ISSUE TITLE
Lista listów

### ISSUE THREAD

**Issue by mateuszmagulski** [watchdogpolska/small_eod#385]
Porównałem wygląd listy listów w wersji demo: https://demo.small-eod.siecobywatelska.pl/
Jeśli chcemy mieć taką samą listę, trzeba wykonać poniższe kroki:

AC1. Model Letter: 
 - [x] usunięcie pola name (pole ~description~ `document_type` je zastępuje) -> #388 

AC2. Zmiana widoku listy listów:
 - [X] usuniecie kolumny nazwa -> (#389, #423) 
 - [x] dodanie kolumny ~opis~`typ dokumentu` (pole ~description.name~`document_type.name` z modelu) (#388, #457)
 - [X] zmiana wyświetlanych informacji w kolumnie kierunek z IN/OUT na odebrane/wysłane (#424)
 - [X] dodanie kolumny instytucja (pole `institution.name` z modelu) (#425)
 - [X] dodanie kolumny data odbioru/data wysłania (format daty: 20 grudnia 2019 11:11, pole date z modelu) (#426) 
 - [X] dodanie kolumny identyfikator (pole identifier z modelu) (to wydaje się, że było od zawsze, od #359)
 - [X] dodanie kolumny spawa (pole case.name z modelu) (#428)
 - [X] dodanie kolumny utworzono (format daty: 20 grudnia 2019 11:11, pole createdOn) (#429)
 - [X] dodanie kolumny modyfikowano (format daty: 20 grudnia 2019 11:11, pole modifiedOn) (#429)
 - [X] dodanie kolumny kanał (pole channel.name z modelu) (#430)
 - [X] dodanie kolumny załącznik (liczba załączników) (#431)

AC3. Stworzenie funkcji do pobierania danych o ~description~`document_type`, institution, channel i case (tutaj wszystko prócz `document_type` dostarczono)

Wszystko rozbiję na małe tematy.

**Comment by ad-m** [comment]
AC1/ 
Sygnatura to identyfikator.
Pole attachment trafiło do osobnego modelu.
Zgadzdam się co do pola "name".
AC2/
> - dodanie kolumny załącznik (tylko z informacją czy jest, czy nie ma załącznika)
Liczba załączników

**Comment by mateuszmagulski** [comment]
zaktualizowane

**Comment by magul** [comment]
@mateuszmagulski @ad-m zaktualizowałem ten ticket zgodnie z wynikami rozmowy z #409 . dodałem informację o podzadaniach przy punkach w kryteriach akceptacji.

@SmietankowyImperator - jakby co można pewnie jakoś porozdzielać te zadania na mniejsze tickety dla początkujących we frontendzie.

**Comment by AgnieszkaZdanowicz** [comment]
AC2. Czy w widoku listy listów będzie też widoczny "komentarz"? Bo w obecnym systemie jest i wolałabym, żeby było widoczne dalej

**Comment by mateuszmagulski** [comment]
Dodałem kolumnę z komentarzem do AC2.

**Comment by mateuszmagulski** [comment]
Na froncie wszystko przygotowane oprócz kolumny typ dokumentu. Tutaj czekam na backend i przemianowanie description na document_type.

**Comment by ad-m** [comment]
Dziękuje za jasne zakomunikowanie braków po stronie back-endu. Zaraz to wykonam.

**Comment by magul** [comment]
@mateuszmagulski został ostatni podpunkt do ogarnięcia. backend wjechał, SDK jest świeża - wystarczy podbić wersję SDK zainstalowaną tutaj w `package.json` (chyba że @renovate-bot zrobi to szybciej) i możesz tą ostatnią kolumnę wyklepać.

**Comment by mateuszmagulski** [comment]
kolumna wyklepana, jak podbić wersję SDK?

**Comment by magul** [comment]
Zrobione w wielu pull requestach, zamykam.
